import fs from "fs";
import path from "path";

async function main() {
  try {
    console.log("Fetching surah list from AlQuran API...");
    const res = await fetch("https://api.alquran.cloud/v1/surah");
    const json = (await res.json()) as any;
    
    if (json.code !== 200 || !json.data) {
      throw new Error(`API returned error: ${JSON.stringify(json)}`);
    }

    const surahs = json.data.map((s: any) => ({
      number: s.number,
      name: s.englishName,
      arabic: s.name,
      english: s.englishNameTranslation,
      verses: s.numberOfAyahs,
      type: s.revelationType
    }));

    const content = `// This file is auto-generated by fetch_surahs.ts
export interface SurahHeader {
  number: number;
  name: string;
  arabic: string;
  english: string;
  verses: number;
  type: "Meccan" | "Medinan";
}

export const SURAH_LIST: SurahHeader[] = ${JSON.stringify(surahs, null, 2)};
`;

    const destPath = path.join(process.cwd(), "src", "surahsData.ts");
    fs.writeFileSync(destPath, content, "utf-8");
    console.log(`Successfully generated 114 surahs in ${destPath}`);
  } catch (err) {
    console.error("Error fetching surahs:", err);
    process.exit(1);
  }
}

main();
