// This file is auto-generated by fetch_surahs.ts
export interface SurahHeader {
  number: number;
  name: string;
  arabic: string;
  english: string;
  verses: number;
  type: "Meccan" | "Medinan";
}

export const SURAH_LIST: SurahHeader[] = [
  {
    "number": 1,
    "name": "Al-Faatiha",
    "arabic": "سُورَةُ ٱلْفَاتِحَةِ",
    "english": "The Opening",
    "verses": 7,
    "type": "Meccan"
  },
  {
    "number": 2,
    "name": "Al-Baqara",
    "arabic": "سُورَةُ البَقَرَةِ",
    "english": "The Cow",
    "verses": 286,
    "type": "Medinan"
  },
  {
    "number": 3,
    "name": "Aal-i-Imraan",
    "arabic": "سُورَةُ آلِ عِمۡرَانَ",
    "english": "The Family of Imraan",
    "verses": 200,
    "type": "Medinan"
  },
  {
    "number": 4,
    "name": "An-Nisaa",
    "arabic": "سُورَةُ النِّسَاءِ",
    "english": "The Women",
    "verses": 176,
    "type": "Medinan"
  },
  {
    "number": 5,
    "name": "Al-Maaida",
    "arabic": "سُورَةُ المَائـِدَةِ",
    "english": "The Table",
    "verses": 120,
    "type": "Medinan"
  },
  {
    "number": 6,
    "name": "Al-An'aam",
    "arabic": "سُورَةُ الأَنۡعَامِ",
    "english": "The Cattle",
    "verses": 165,
    "type": "Meccan"
  },
  {
    "number": 7,
    "name": "Al-A'raaf",
    "arabic": "سُورَةُ الأَعۡرَافِ",
    "english": "The Heights",
    "verses": 206,
    "type": "Meccan"
  },
  {
    "number": 8,
    "name": "Al-Anfaal",
    "arabic": "سُورَةُ الأَنفَالِ",
    "english": "The Spoils of War",
    "verses": 75,
    "type": "Medinan"
  },
  {
    "number": 9,
    "name": "At-Tawba",
    "arabic": "سُورَةُ التَّوۡبَةِ",
    "english": "The Repentance",
    "verses": 129,
    "type": "Medinan"
  },
  {
    "number": 10,
    "name": "Yunus",
    "arabic": "سُورَةُ يُونُسَ",
    "english": "Jonas",
    "verses": 109,
    "type": "Meccan"
  },
  {
    "number": 11,
    "name": "Hud",
    "arabic": "سُورَةُ هُودٍ",
    "english": "Hud",
    "verses": 123,
    "type": "Meccan"
  },
  {
    "number": 12,
    "name": "Yusuf",
    "arabic": "سُورَةُ يُوسُفَ",
    "english": "Joseph",
    "verses": 111,
    "type": "Meccan"
  },
  {
    "number": 13,
    "name": "Ar-Ra'd",
    "arabic": "سُورَةُ الرَّعۡدِ",
    "english": "The Thunder",
    "verses": 43,
    "type": "Medinan"
  },
  {
    "number": 14,
    "name": "Ibrahim",
    "arabic": "سُورَةُ إِبۡرَاهِيمَ",
    "english": "Abraham",
    "verses": 52,
    "type": "Meccan"
  },
  {
    "number": 15,
    "name": "Al-Hijr",
    "arabic": "سُورَةُ الحِجۡرِ",
    "english": "The Rock",
    "verses": 99,
    "type": "Meccan"
  },
  {
    "number": 16,
    "name": "An-Nahl",
    "arabic": "سُورَةُ النَّحۡلِ",
    "english": "The Bee",
    "verses": 128,
    "type": "Meccan"
  },
  {
    "number": 17,
    "name": "Al-Israa",
    "arabic": "سُورَةُ الإِسۡرَاءِ",
    "english": "The Night Journey",
    "verses": 111,
    "type": "Meccan"
  },
  {
    "number": 18,
    "name": "Al-Kahf",
    "arabic": "سُورَةُ الكَهۡفِ",
    "english": "The Cave",
    "verses": 110,
    "type": "Meccan"
  },
  {
    "number": 19,
    "name": "Maryam",
    "arabic": "سُورَةُ مَرۡيَمَ",
    "english": "Mary",
    "verses": 98,
    "type": "Meccan"
  },
  {
    "number": 20,
    "name": "Taa-Haa",
    "arabic": "سُورَةُ طه",
    "english": "Taa-Haa",
    "verses": 135,
    "type": "Meccan"
  },
  {
    "number": 21,
    "name": "Al-Anbiyaa",
    "arabic": "سُورَةُ الأَنبِيَاءِ",
    "english": "The Prophets",
    "verses": 112,
    "type": "Meccan"
  },
  {
    "number": 22,
    "name": "Al-Hajj",
    "arabic": "سُورَةُ الحَجِّ",
    "english": "The Pilgrimage",
    "verses": 78,
    "type": "Medinan"
  },
  {
    "number": 23,
    "name": "Al-Muminoon",
    "arabic": "سُورَةُ المُؤۡمِنُونَ",
    "english": "The Believers",
    "verses": 118,
    "type": "Meccan"
  },
  {
    "number": 24,
    "name": "An-Noor",
    "arabic": "سُورَةُ النُّورِ",
    "english": "The Light",
    "verses": 64,
    "type": "Medinan"
  },
  {
    "number": 25,
    "name": "Al-Furqaan",
    "arabic": "سُورَةُ الفُرۡقَانِ",
    "english": "The Criterion",
    "verses": 77,
    "type": "Meccan"
  },
  {
    "number": 26,
    "name": "Ash-Shu'araa",
    "arabic": "سُورَةُ الشُّعَرَاءِ",
    "english": "The Poets",
    "verses": 227,
    "type": "Meccan"
  },
  {
    "number": 27,
    "name": "An-Naml",
    "arabic": "سُورَةُ النَّمۡلِ",
    "english": "The Ant",
    "verses": 93,
    "type": "Meccan"
  },
  {
    "number": 28,
    "name": "Al-Qasas",
    "arabic": "سُورَةُ القَصَصِ",
    "english": "The Stories",
    "verses": 88,
    "type": "Meccan"
  },
  {
    "number": 29,
    "name": "Al-Ankaboot",
    "arabic": "سُورَةُ العَنكَبُوتِ",
    "english": "The Spider",
    "verses": 69,
    "type": "Meccan"
  },
  {
    "number": 30,
    "name": "Ar-Room",
    "arabic": "سُورَةُ الرُّومِ",
    "english": "The Romans",
    "verses": 60,
    "type": "Meccan"
  },
  {
    "number": 31,
    "name": "Luqman",
    "arabic": "سُورَةُ لُقۡمَانَ",
    "english": "Luqman",
    "verses": 34,
    "type": "Meccan"
  },
  {
    "number": 32,
    "name": "As-Sajda",
    "arabic": "سُورَةُ السَّجۡدَةِ",
    "english": "The Prostration",
    "verses": 30,
    "type": "Meccan"
  },
  {
    "number": 33,
    "name": "Al-Ahzaab",
    "arabic": "سُورَةُ الأَحۡزَابِ",
    "english": "The Clans",
    "verses": 73,
    "type": "Medinan"
  },
  {
    "number": 34,
    "name": "Saba",
    "arabic": "سُورَةُ سَبَإٍ",
    "english": "Sheba",
    "verses": 54,
    "type": "Meccan"
  },
  {
    "number": 35,
    "name": "Faatir",
    "arabic": "سُورَةُ فَاطِرٍ",
    "english": "The Originator",
    "verses": 45,
    "type": "Meccan"
  },
  {
    "number": 36,
    "name": "Yaseen",
    "arabic": "سُورَةُ يسٓ",
    "english": "Yaseen",
    "verses": 83,
    "type": "Meccan"
  },
  {
    "number": 37,
    "name": "As-Saaffaat",
    "arabic": "سُورَةُ الصَّافَّاتِ",
    "english": "Those drawn up in Ranks",
    "verses": 182,
    "type": "Meccan"
  },
  {
    "number": 38,
    "name": "Saad",
    "arabic": "سُورَةُ صٓ",
    "english": "The letter Saad",
    "verses": 88,
    "type": "Meccan"
  },
  {
    "number": 39,
    "name": "Az-Zumar",
    "arabic": "سُورَةُ الزُّمَرِ",
    "english": "The Groups",
    "verses": 75,
    "type": "Meccan"
  },
  {
    "number": 40,
    "name": "Ghafir",
    "arabic": "سُورَةُ غَافِرٍ",
    "english": "The Forgiver",
    "verses": 85,
    "type": "Meccan"
  },
  {
    "number": 41,
    "name": "Fussilat",
    "arabic": "سُورَةُ فُصِّلَتۡ",
    "english": "Explained in detail",
    "verses": 54,
    "type": "Meccan"
  },
  {
    "number": 42,
    "name": "Ash-Shura",
    "arabic": "سُورَةُ الشُّورَىٰ",
    "english": "Consultation",
    "verses": 53,
    "type": "Meccan"
  },
  {
    "number": 43,
    "name": "Az-Zukhruf",
    "arabic": "سُورَةُ الزُّخۡرُفِ",
    "english": "Ornaments of gold",
    "verses": 89,
    "type": "Meccan"
  },
  {
    "number": 44,
    "name": "Ad-Dukhaan",
    "arabic": "سُورَةُ الدُّخَانِ",
    "english": "The Smoke",
    "verses": 59,
    "type": "Meccan"
  },
  {
    "number": 45,
    "name": "Al-Jaathiya",
    "arabic": "سُورَةُ الجَاثِيَةِ",
    "english": "Crouching",
    "verses": 37,
    "type": "Meccan"
  },
  {
    "number": 46,
    "name": "Al-Ahqaf",
    "arabic": "سُورَةُ الأَحۡقَافِ",
    "english": "The Dunes",
    "verses": 35,
    "type": "Meccan"
  },
  {
    "number": 47,
    "name": "Muhammad",
    "arabic": "سُورَةُ مُحَمَّدٍ",
    "english": "Muhammad",
    "verses": 38,
    "type": "Medinan"
  },
  {
    "number": 48,
    "name": "Al-Fath",
    "arabic": "سُورَةُ الفَتۡحِ",
    "english": "The Victory",
    "verses": 29,
    "type": "Medinan"
  },
  {
    "number": 49,
    "name": "Al-Hujuraat",
    "arabic": "سُورَةُ الحُجُرَاتِ",
    "english": "The Inner Apartments",
    "verses": 18,
    "type": "Medinan"
  },
  {
    "number": 50,
    "name": "Qaaf",
    "arabic": "سُورَةُ قٓ",
    "english": "The letter Qaaf",
    "verses": 45,
    "type": "Meccan"
  },
  {
    "number": 51,
    "name": "Adh-Dhaariyat",
    "arabic": "سُورَةُ الذَّارِيَاتِ",
    "english": "The Winnowing Winds",
    "verses": 60,
    "type": "Meccan"
  },
  {
    "number": 52,
    "name": "At-Tur",
    "arabic": "سُورَةُ الطُّورِ",
    "english": "The Mount",
    "verses": 49,
    "type": "Meccan"
  },
  {
    "number": 53,
    "name": "An-Najm",
    "arabic": "سُورَةُ النَّجۡمِ",
    "english": "The Star",
    "verses": 62,
    "type": "Meccan"
  },
  {
    "number": 54,
    "name": "Al-Qamar",
    "arabic": "سُورَةُ القَمَرِ",
    "english": "The Moon",
    "verses": 55,
    "type": "Meccan"
  },
  {
    "number": 55,
    "name": "Ar-Rahmaan",
    "arabic": "سُورَةُ الرَّحۡمَٰن",
    "english": "The Beneficent",
    "verses": 78,
    "type": "Medinan"
  },
  {
    "number": 56,
    "name": "Al-Waaqia",
    "arabic": "سُورَةُ الوَاقِعَةِ",
    "english": "The Inevitable",
    "verses": 96,
    "type": "Meccan"
  },
  {
    "number": 57,
    "name": "Al-Hadid",
    "arabic": "سُورَةُ الحَدِيدِ",
    "english": "The Iron",
    "verses": 29,
    "type": "Medinan"
  },
  {
    "number": 58,
    "name": "Al-Mujaadila",
    "arabic": "سُورَةُ المُجَادلَةِ",
    "english": "The Pleading Woman",
    "verses": 22,
    "type": "Medinan"
  },
  {
    "number": 59,
    "name": "Al-Hashr",
    "arabic": "سُورَةُ الحَشۡرِ",
    "english": "The Exile",
    "verses": 24,
    "type": "Medinan"
  },
  {
    "number": 60,
    "name": "Al-Mumtahana",
    "arabic": "سُورَةُ المُمۡتَحنَةِ",
    "english": "She that is to be examined",
    "verses": 13,
    "type": "Medinan"
  },
  {
    "number": 61,
    "name": "As-Saff",
    "arabic": "سُورَةُ الصَّفِّ",
    "english": "The Ranks",
    "verses": 14,
    "type": "Medinan"
  },
  {
    "number": 62,
    "name": "Al-Jumu'a",
    "arabic": "سُورَةُ الجُمُعَةِ",
    "english": "Friday",
    "verses": 11,
    "type": "Medinan"
  },
  {
    "number": 63,
    "name": "Al-Munaafiqoon",
    "arabic": "سُورَةُ المُنَافِقُونَ",
    "english": "The Hypocrites",
    "verses": 11,
    "type": "Medinan"
  },
  {
    "number": 64,
    "name": "At-Taghaabun",
    "arabic": "سُورَةُ التَّغَابُنِ",
    "english": "Mutual Disillusion",
    "verses": 18,
    "type": "Medinan"
  },
  {
    "number": 65,
    "name": "At-Talaaq",
    "arabic": "سُورَةُ الطَّلَاقِ",
    "english": "Divorce",
    "verses": 12,
    "type": "Medinan"
  },
  {
    "number": 66,
    "name": "At-Tahrim",
    "arabic": "سُورَةُ التَّحۡرِيمِ",
    "english": "The Prohibition",
    "verses": 12,
    "type": "Medinan"
  },
  {
    "number": 67,
    "name": "Al-Mulk",
    "arabic": "سُورَةُ المُلۡكِ",
    "english": "The Sovereignty",
    "verses": 30,
    "type": "Meccan"
  },
  {
    "number": 68,
    "name": "Al-Qalam",
    "arabic": "سُورَةُ القَلَمِ",
    "english": "The Pen",
    "verses": 52,
    "type": "Meccan"
  },
  {
    "number": 69,
    "name": "Al-Haaqqa",
    "arabic": "سُورَةُ الحَاقَّةِ",
    "english": "The Reality",
    "verses": 52,
    "type": "Meccan"
  },
  {
    "number": 70,
    "name": "Al-Ma'aarij",
    "arabic": "سُورَةُ المَعَارِجِ",
    "english": "The Ascending Stairways",
    "verses": 44,
    "type": "Meccan"
  },
  {
    "number": 71,
    "name": "Nooh",
    "arabic": "سُورَةُ نُوحٍ",
    "english": "Noah",
    "verses": 28,
    "type": "Meccan"
  },
  {
    "number": 72,
    "name": "Al-Jinn",
    "arabic": "سُورَةُ الجِنِّ",
    "english": "The Jinn",
    "verses": 28,
    "type": "Meccan"
  },
  {
    "number": 73,
    "name": "Al-Muzzammil",
    "arabic": "سُورَةُ المُزَّمِّلِ",
    "english": "The Enshrouded One",
    "verses": 20,
    "type": "Meccan"
  },
  {
    "number": 74,
    "name": "Al-Muddaththir",
    "arabic": "سُورَةُ المُدَّثِّرِ",
    "english": "The Cloaked One",
    "verses": 56,
    "type": "Meccan"
  },
  {
    "number": 75,
    "name": "Al-Qiyaama",
    "arabic": "سُورَةُ القِيَامَةِ",
    "english": "The Resurrection",
    "verses": 40,
    "type": "Meccan"
  },
  {
    "number": 76,
    "name": "Al-Insaan",
    "arabic": "سُورَةُ الإِنسَانِ",
    "english": "Man",
    "verses": 31,
    "type": "Medinan"
  },
  {
    "number": 77,
    "name": "Al-Mursalaat",
    "arabic": "سُورَةُ المُرۡسَلَاتِ",
    "english": "The Emissaries",
    "verses": 50,
    "type": "Meccan"
  },
  {
    "number": 78,
    "name": "An-Naba",
    "arabic": "سُورَةُ النَّبَإِ",
    "english": "The Announcement",
    "verses": 40,
    "type": "Meccan"
  },
  {
    "number": 79,
    "name": "An-Naazi'aat",
    "arabic": "سُورَةُ النَّازِعَاتِ",
    "english": "Those who drag forth",
    "verses": 46,
    "type": "Meccan"
  },
  {
    "number": 80,
    "name": "Abasa",
    "arabic": "سُورَةُ عَبَسَ",
    "english": "He frowned",
    "verses": 42,
    "type": "Meccan"
  },
  {
    "number": 81,
    "name": "At-Takwir",
    "arabic": "سُورَةُ التَّكۡوِيرِ",
    "english": "The Overthrowing",
    "verses": 29,
    "type": "Meccan"
  },
  {
    "number": 82,
    "name": "Al-Infitaar",
    "arabic": "سُورَةُ الانفِطَارِ",
    "english": "The Cleaving",
    "verses": 19,
    "type": "Meccan"
  },
  {
    "number": 83,
    "name": "Al-Mutaffifin",
    "arabic": "سُورَةُ المُطَفِّفِينَ",
    "english": "Defrauding",
    "verses": 36,
    "type": "Meccan"
  },
  {
    "number": 84,
    "name": "Al-Inshiqaaq",
    "arabic": "سُورَةُ الانشِقَاقِ",
    "english": "The Splitting Open",
    "verses": 25,
    "type": "Meccan"
  },
  {
    "number": 85,
    "name": "Al-Burooj",
    "arabic": "سُورَةُ البُرُوجِ",
    "english": "The Constellations",
    "verses": 22,
    "type": "Meccan"
  },
  {
    "number": 86,
    "name": "At-Taariq",
    "arabic": "سُورَةُ الطَّارِقِ",
    "english": "The Morning Star",
    "verses": 17,
    "type": "Meccan"
  },
  {
    "number": 87,
    "name": "Al-A'laa",
    "arabic": "سُورَةُ الأَعۡلَىٰ",
    "english": "The Most High",
    "verses": 19,
    "type": "Meccan"
  },
  {
    "number": 88,
    "name": "Al-Ghaashiya",
    "arabic": "سُورَةُ الغَاشِيَةِ",
    "english": "The Overwhelming",
    "verses": 26,
    "type": "Meccan"
  },
  {
    "number": 89,
    "name": "Al-Fajr",
    "arabic": "سُورَةُ الفَجۡرِ",
    "english": "The Dawn",
    "verses": 30,
    "type": "Meccan"
  },
  {
    "number": 90,
    "name": "Al-Balad",
    "arabic": "سُورَةُ البَلَدِ",
    "english": "The City",
    "verses": 20,
    "type": "Meccan"
  },
  {
    "number": 91,
    "name": "Ash-Shams",
    "arabic": "سُورَةُ الشَّمۡسِ",
    "english": "The Sun",
    "verses": 15,
    "type": "Meccan"
  },
  {
    "number": 92,
    "name": "Al-Lail",
    "arabic": "سُورَةُ اللَّيۡلِ",
    "english": "The Night",
    "verses": 21,
    "type": "Meccan"
  },
  {
    "number": 93,
    "name": "Ad-Dhuhaa",
    "arabic": "سُورَةُ الضُّحَىٰ",
    "english": "The Morning Hours",
    "verses": 11,
    "type": "Meccan"
  },
  {
    "number": 94,
    "name": "Ash-Sharh",
    "arabic": "سُورَةُ الشَّرۡحِ",
    "english": "The Consolation",
    "verses": 8,
    "type": "Meccan"
  },
  {
    "number": 95,
    "name": "At-Tin",
    "arabic": "سُورَةُ التِّينِ",
    "english": "The Fig",
    "verses": 8,
    "type": "Meccan"
  },
  {
    "number": 96,
    "name": "Al-Alaq",
    "arabic": "سُورَةُ العَلَقِ",
    "english": "The Clot",
    "verses": 19,
    "type": "Meccan"
  },
  {
    "number": 97,
    "name": "Al-Qadr",
    "arabic": "سُورَةُ القَدۡرِ",
    "english": "The Power, Fate",
    "verses": 5,
    "type": "Meccan"
  },
  {
    "number": 98,
    "name": "Al-Bayyina",
    "arabic": "سُورَةُ البَيِّنَةِ",
    "english": "The Evidence",
    "verses": 8,
    "type": "Medinan"
  },
  {
    "number": 99,
    "name": "Az-Zalzala",
    "arabic": "سُورَةُ الزَّلۡزَلَةِ",
    "english": "The Earthquake",
    "verses": 8,
    "type": "Medinan"
  },
  {
    "number": 100,
    "name": "Al-Aadiyaat",
    "arabic": "سُورَةُ العَادِيَاتِ",
    "english": "The Chargers",
    "verses": 11,
    "type": "Meccan"
  },
  {
    "number": 101,
    "name": "Al-Qaari'a",
    "arabic": "سُورَةُ القَارِعَةِ",
    "english": "The Calamity",
    "verses": 11,
    "type": "Meccan"
  },
  {
    "number": 102,
    "name": "At-Takaathur",
    "arabic": "سُورَةُ التَّكَاثُرِ",
    "english": "Competition",
    "verses": 8,
    "type": "Meccan"
  },
  {
    "number": 103,
    "name": "Al-Asr",
    "arabic": "سُورَةُ العَصۡرِ",
    "english": "The Declining Day, Epoch",
    "verses": 3,
    "type": "Meccan"
  },
  {
    "number": 104,
    "name": "Al-Humaza",
    "arabic": "سُورَةُ الهُمَزَةِ",
    "english": "The Traducer",
    "verses": 9,
    "type": "Meccan"
  },
  {
    "number": 105,
    "name": "Al-Fil",
    "arabic": "سُورَةُ الفِيلِ",
    "english": "The Elephant",
    "verses": 5,
    "type": "Meccan"
  },
  {
    "number": 106,
    "name": "Quraish",
    "arabic": "سُورَةُ قُرَيۡشٍ",
    "english": "Quraysh",
    "verses": 4,
    "type": "Meccan"
  },
  {
    "number": 107,
    "name": "Al-Maa'un",
    "arabic": "سُورَةُ المَاعُونِ",
    "english": "Almsgiving",
    "verses": 7,
    "type": "Meccan"
  },
  {
    "number": 108,
    "name": "Al-Kawthar",
    "arabic": "سُورَةُ الكَوۡثَرِ",
    "english": "Abundance",
    "verses": 3,
    "type": "Meccan"
  },
  {
    "number": 109,
    "name": "Al-Kaafiroon",
    "arabic": "سُورَةُ الكَافِرُونَ",
    "english": "The Disbelievers",
    "verses": 6,
    "type": "Meccan"
  },
  {
    "number": 110,
    "name": "An-Nasr",
    "arabic": "سُورَةُ النَّصۡرِ",
    "english": "Divine Support",
    "verses": 3,
    "type": "Medinan"
  },
  {
    "number": 111,
    "name": "Al-Masad",
    "arabic": "سُورَةُ المَسَدِ",
    "english": "The Palm Fibre",
    "verses": 5,
    "type": "Meccan"
  },
  {
    "number": 112,
    "name": "Al-Ikhlaas",
    "arabic": "سُورَةُ الإِخۡلَاصِ",
    "english": "Sincerity",
    "verses": 4,
    "type": "Meccan"
  },
  {
    "number": 113,
    "name": "Al-Falaq",
    "arabic": "سُورَةُ الفَلَقِ",
    "english": "The Dawn",
    "verses": 5,
    "type": "Meccan"
  },
  {
    "number": 114,
    "name": "An-Naas",
    "arabic": "سُورَةُ النَّاسِ",
    "english": "Mankind",
    "verses": 6,
    "type": "Meccan"
  }
];
